### ISSUE TITLE
ConnectionCandidate

### ISSUE THREAD

**Issue by developercrazy021** [easynearby/EasyNearby#1]
Hello and don't be tired
Thank you for your very good lib
I have a question
I want to enable connection based on QrCode in my software
And for this, I need to access the ConnectionCandidate of the person who is in Advertising mode
How can I have this parameter?

**Comment by gusakovgiorgi** [comment]
Hi @smartmob021
I'm glad that you've found the library useful.
When you start discovery you'll get `ConnectionCandidate`'s once they're discovered.

```fun start(deviceInfo: DeviceInfo) {
    viewModelScope.launch {
        EasyNearby.getDiscoverManager().startDiscovery(deviceInfo)
            .onSuccess {
                // --> Here it keyword will refer to the discovered connection candidate.
            }.onFailure {
                // Handle failure
            }
    }
}```

Does it answer your question? Let me know if you have issue.

**Comment by developercrazy021** [comment]
In startDiscovery, it gives us the information of the persons who request connection
I want the get ConnectionCandidate my self
If it is already available , I would appreciate it if you could give me a sample
tnx

**Comment by gusakovgiorgi** [comment]
What's the purpose of your QA code? Do you want to share your ID in order to other device can connect to you? Other devices can connect to you after discovery. The connection is identified via unique Id that google library assigns to you.

**Comment by developercrazy021** [comment]
Yes, the purpose of QrCode is what you said. Sometimes it has happened that some devices do not find each other. This is where you need to connect by QrCode. According to the Zapya or ShareIt application, which have used the feature along with other offline connection features.
I need to get the ConnectionCandidate of the person who clicked on the Advertising option first. Or have the unique ID that Google has assigned to the device, so that I can create my QrCode and provide direct connection procedures.

**Comment by gusakovgiorgi** [comment]
Unfortunately I don't see the option of getting endpoint Id using google nearby library
https://developers.google.com/android/reference/com/google/android/gms/nearby/connection/ConnectionsClient#startAdvertising(byte[],%20java.lang.String,%20com.google.android.gms.nearby.connection.ConnectionLifecycleCallback,%20com.google.android.gms.nearby.connection.AdvertisingOptions)

In order to connect to a remote device it should be discovered first. Qr code should be useful to filter the needed device between all discovered devices. But for this purpose you can use name.

I'll try to check later if somehow I can get endpoint Id when I start advertisning.

**Comment by developercrazy021** [comment]
tnx
